/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import beans.Filme;
import dao.FilmeDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class FormsFilme extends javax.swing.JFrame {

    /**
     * Creates new form FormsFilme
     */
    public FormsFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TXTtitulo = new javax.swing.JTextField();
        TXTdiretor = new javax.swing.JTextField();
        TXTano = new javax.swing.JTextField();
        TXTgenero = new javax.swing.JTextField();
        TXTidioma = new javax.swing.JTextField();
        TXTpais = new javax.swing.JTextField();
        TXTassistido = new javax.swing.JTextField();
        TXTavaliacao = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        TXTduracao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        TXTbuscar = new javax.swing.JTextField();
        BTNbuscar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        TXTID = new javax.swing.JTextField();
        BTNeditar = new javax.swing.JToggleButton();
        BTNexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("FilmTrackr");
        jLabel2.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel13.setText("Título");

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel14.setText("Diretor");

        jLabel15.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel15.setText("Ano");

        jLabel16.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel16.setText("Gênero");

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel17.setText("Duração");

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel18.setText("Idioma");

        jLabel19.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel19.setText("País ");

        jLabel20.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel20.setText("Assistido");

        jLabel21.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel21.setText("Avaliação");

        TXTtitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtituloActionPerformed(evt);
            }
        });

        TXTdiretor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTdiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTdiretorActionPerformed(evt);
            }
        });

        TXTano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTanoActionPerformed(evt);
            }
        });

        TXTgenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTgeneroActionPerformed(evt);
            }
        });

        TXTidioma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTidioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidiomaActionPerformed(evt);
            }
        });

        TXTpais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpaisActionPerformed(evt);
            }
        });

        TXTassistido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTassistido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTassistidoActionPerformed(evt);
            }
        });

        TXTavaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTavaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTavaliacaoActionPerformed(evt);
            }
        });

        Salvar.setBackground(new java.awt.Color(204, 204, 204));
        Salvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        TXTduracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTduracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTduracaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar filme pelo ID:");

        BTNbuscar.setBackground(new java.awt.Color(204, 204, 204));
        BTNbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNbuscar.setText("Buscar");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel3.setText("ID");

        TXTID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTID.setEnabled(false);

        BTNeditar.setBackground(new java.awt.Color(204, 204, 204));
        BTNeditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNeditar.setText("Editar");
        BTNeditar.setMaximumSize(new java.awt.Dimension(70, 30));
        BTNeditar.setMinimumSize(new java.awt.Dimension(70, 30));
        BTNeditar.setPreferredSize(new java.awt.Dimension(70, 30));
        BTNeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeditarActionPerformed(evt);
            }
        });

        BTNexcluir.setBackground(new java.awt.Color(204, 204, 204));
        BTNexcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNexcluir.setText("Excluir");
        BTNexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTano, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTtitulo)
                                    .addComponent(TXTdiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTavaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTassistido, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTduracao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTpais, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNexcluir)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(TXTID, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TXTdiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TXTano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TXTgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TXTduracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TXTidioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTassistido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TXTavaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salvar)
                    .addComponent(BTNexcluir)
                    .addComponent(BTNeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTtituloActionPerformed

    private void TXTdiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTdiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTdiretorActionPerformed

    private void TXTanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTanoActionPerformed

    private void TXTgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTgeneroActionPerformed

    private void TXTidiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidiomaActionPerformed

    private void TXTpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpaisActionPerformed

    private void TXTavaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTavaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTavaliacaoActionPerformed

    private void TXTassistidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTassistidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTassistidoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
// TODO add your handling code here:
        String titulo = TXTtitulo.getText();
        String diretor = TXTdiretor.getText();
        int ano = Integer.parseInt(TXTano.getText());
        String genero = TXTgenero.getText();
        double duracao = Double.parseDouble(TXTduracao.getText());
        String idioma = TXTidioma.getText();
        String pais = TXTpais.getText();
        String assistido = TXTassistido.getText();
        double avaliacao = Double.parseDouble(TXTavaliacao.getText());
        
        Filme filme = new Filme();
        filme.setTitulo(titulo);
        filme.setDiretor(diretor);
        filme.setAnoLancamento(ano);
        filme.setGenero(genero);
        filme.setDuracao(duracao);
        filme.setIdioma(idioma);
        filme.setPaisOrigem(pais);
        filme.setAssistido(assistido);
        filme.setAvaliacao(avaliacao);
        
        FilmeDAO filmeDAO = new FilmeDAO();
        filmeDAO.inserir(filme);
   
        TXTtitulo.setText("");
        TXTdiretor.setText("");
        TXTano.setText("");
        TXTgenero.setText("");
        TXTduracao.setText("");
        TXTidioma.setText("");
        TXTpais.setText("");
        TXTassistido.setText("");
        TXTavaliacao.setText("");
        
        
    }//GEN-LAST:event_SalvarActionPerformed

    private void TXTduracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTduracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTduracaoActionPerformed

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarActionPerformed
        // TODO add your handling code here:
        int idPesquisa = Integer.parseInt(TXTbuscar.getText());
        FilmeDAO filmeDAO = new FilmeDAO();
        Filme filme = filmeDAO.getFilme(idPesquisa);
        if(filme == null){
            JOptionPane.showMessageDialog(this, "Filme não encontrado");
        }
        else{
            TXTID.setText(String.valueOf(filme.getId()));
            TXTtitulo.setText(filme.getTitulo());
            TXTdiretor.setText(filme.getDiretor());
            TXTano.setText(String.valueOf(filme.getAnoLancamento()));
            TXTgenero.setText(filme.getGenero());
            TXTduracao.setText(String.valueOf(filme.getDuracao()));
            TXTidioma.setText(filme.getIdioma());
            TXTpais.setText(filme.getPaisOrigem());
            TXTassistido.setText(filme.getAssistido());
            TXTavaliacao.setText(String.valueOf(filme.getAvaliacao()));
        
        }
        
    }//GEN-LAST:event_BTNbuscarActionPerformed

    private void BTNeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeditarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(TXTID.getText());
        String titulo = TXTtitulo.getText();
        String diretor = TXTdiretor.getText();
        int ano = Integer.parseInt(TXTano.getText());
        String genero = TXTgenero.getText();
        double duracao = Double.parseDouble(TXTduracao.getText());
        String idioma = TXTidioma.getText();
        String pais = TXTpais.getText();
        String assistido = TXTassistido.getText();
        double avaliacao = Double.parseDouble(TXTavaliacao.getText());

        Filme filme = new Filme();
        filme.setId(id);
        filme.setTitulo(titulo);
        filme.setDiretor(diretor);
        filme.setAnoLancamento(ano);
        filme.setGenero(genero);
        filme.setDuracao(duracao);
        filme.setIdioma(idioma);
        filme.setPaisOrigem(pais);
        filme.setAssistido(assistido);
        filme.setAvaliacao(avaliacao);

        FilmeDAO filmeDAO = new FilmeDAO();
        filmeDAO.editar(filme);

        TXTID.setText("");
        TXTtitulo.setText("");
        TXTdiretor.setText("");
        TXTano.setText("");
        TXTgenero.setText("");
        TXTduracao.setText("");
        TXTidioma.setText("");
        TXTpais.setText("");
        TXTassistido.setText("");
        TXTavaliacao.setText("");
    }//GEN-LAST:event_BTNeditarActionPerformed

    private void BTNexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(TXTID.getText());
        FilmeDAO filmeDAO = new FilmeDAO();
        filmeDAO.excluir(id);
        
        TXTID.setText("");
        TXTtitulo.setText("");
        TXTdiretor.setText("");
        TXTano.setText("");
        TXTgenero.setText("");
        TXTduracao.setText("");
        TXTidioma.setText("");
        TXTpais.setText("");
        TXTassistido.setText("");
        TXTavaliacao.setText("");
    }//GEN-LAST:event_BTNexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormsFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTNbuscar;
    private javax.swing.JToggleButton BTNeditar;
    private javax.swing.JButton BTNexcluir;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTano;
    private javax.swing.JTextField TXTassistido;
    private javax.swing.JTextField TXTavaliacao;
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JTextField TXTdiretor;
    private javax.swing.JTextField TXTduracao;
    private javax.swing.JTextField TXTgenero;
    private javax.swing.JTextField TXTidioma;
    private javax.swing.JTextField TXTpais;
    private javax.swing.JTextField TXTtitulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
